source "https://rubygems.org"
ruby "~> 3.3"

gem "rails", "~> 7.2"
gem "puma", ">= 5.0"
gem "sqlite3", ">= 1.4"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "debug"
end
